baseurl = "https://pfhawkins.com/" # TODO
builddrafts = false
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
# disqusShortname = "cocoaexamplesite" # TODO: optional, comment out to disable Disqus
pluralizelisttitles = false

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"



[permalinks]
fixed = ":title/"
blog = ":slug/"

[params]
author = "P.F. Hawkins"
title = "P.F. Hawkinsâ€™ Dot Com"
cachebuster = true
dateform = "2006-01-02"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "a commonplace of sorts"
email = "pf@pfhawkins.com" # TODO:
faviconfile = "favicon.png"
gatracker = "XYZ" # TODO:
github = "//github.com/pfhawkins" # TODO:
#gravatar = "7033d0e84d10d256a4b850461f69a10b"
#initials = "P.F.H." # displayed on single post page; DEPRECATED in v0.3.0
lang = "en"
#linkedin = "//linkedin.com/in/patrickhawkins1" # TODO:
#twitter = "//twitter.com/pfhawkins" # TODO:
ignoreLogs = ['warning-goldmark-raw-html']
